export const SUCCESS_PROJECT_AXIOS = "SUCCESS_PROJECT_AXIOS";
export const FAILURE_PROJECT_AXIOS = "FAILURE_PROJECT_AXIOS";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT= "UPDATE_PROJECT";

export const SUCCESS_SKILL_AXIOS = "SUCCESS_SKILL_AXIOS";
export const FAILURE_SKILL_AXIOS = "FAILURE_SKILL_AXIOS";
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";

export const SUCCESS_LIBRARY_AXIOS = "SUCCESS_LIBRARY_AXIOS";
export const FAILURE_LIBRARY_AXIOS = "FAILURE_LIBRARY_AXIOS";
export const ADD_LIBRARY = "ADD_LIBRARY";
export const DELETE_LIBRARY = "DELETE_LIBRARY";
export const UPDATE_LIBRARY = "UPDATE_LIBRARY";